# STAGE 1: Build Stage
FROM node:alpine3.21 AS builder

WORKDIR /usr/src/app

COPY worker/package*.json ./

RUN npm install

COPY worker ./

RUN npm run build


# STAGE 2: Production Stage
FROM node:alpine3.21

WORKDIR /usr/src/app

COPY worker/package*.json ./

RUN npm ci --omit=dev

COPY --from=builder /usr/src/app/build ./build

CMD ["node", "./build/src/index.js"]
